### ISSUE TITLE
Can you make inpainting mode more easy to use? that will be great

### ISSUE THREAD

**Issue by putuoka** [fishslot/video_loopback_for_webui#13]
i use this video loop to generating awesome image because it can fix hand in 10 loop so i want to try this with inpainting but always getting an error. can u make it easier to use like only use mask from original inpainting board no need to set up anything just use inpainting original board with video loop. this extention is very good in generation image better than normal txt2img it can fix hand in 10 loop and can fix whole generation quality as well

**Comment by fishslot** [comment]
Perhaps you could describe the problem in more detail so that I can fix it?
Have you checked the `use_mask` option and fill the `mask_directory` with the directory of your mask image?
Use mask from original inpainting board may affect other inpainting function, I wil be more cautious about the changes to it.

**Comment by putuoka** [comment]
> Perhaps you could describe the problem in more detail so that I can fix it? Have you checked the `use_mask` option and fill the `mask_directory` with the directory of your mask image? Use mask from original inpainting board may affect other inpainting function, I wil be more cautious about the changes to it.

ok i will try explaining the error i got or may be a view to make it clear i don't know what is the mask image that cause the error. first i try normal image with black face the tools say need alpha channel mask, second i try withtransparent png image the tools error say wait i forgot
