### ISSUE TITLE
hello, how to continue job?

### ISSUE THREAD

**Issue by tembel123456** [fishslot/video_loopback_for_webui#14]
first, sorry for my english...

second - i'am new with SD, but try use you extension, and is GREAT.

just have a problem... how to continue job, when i need create , for example, 3 more loops ?

using inpainting or img2img, have folder with started frames, generate , for example `10 loops, but when see a result, i'am need next , couple loops... how to continue that job, without starting from the beginning...  

Thanx for any help...

Regards

**Comment by moon47usaco** [comment]
This is a good question. It would be nice to be able to resume if the there is a crash since this process is very long.
Can you just use the frames from the last loop created to start another 3 loops?
Would that produce the same result?

**Comment by tembel123456** [comment]
i' try that way, but don't know, if that create the same result..  i thing result is different..
can't compare for now,  not too many jobs i try..  have LOW card PC, slow and old, so every job, cost some hours )
  resume will be really great option

**Comment by fishslot** [comment]
@moon47usaco is right, set the `inpust_dir` to the loop file you want to countinue, it works well and is the same as running directly from the beginning, at least in the current version. Unless the `temporal_superimpose_method` is not `simple` and `reference_frames_directory` is empty, in which case you need to fill in the `reference_frames_directory` with the original `output_directory`.

**Comment by tembel123456** [comment]
thanx will try.. best script for SD...  )))

**Comment by moon47usaco** [comment]
If you need faster rendering of jobs try a google colab.

Its free for minimal use but if you need more time its the cheapest cloud option.

I like the one here:
[https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb](url)

Another cloud service is https://rundiffusion.com easier to use with preloaded extensions although much more expensive for the. same computing power.
