### ISSUE TITLE
reference_frames_directory get Error when its empty

### ISSUE THREAD

**Issue by keyskull** [fishslot/video_loopback_for_webui#16]
Instanclize TemporalImageBlender error:

stable-diffusion-webui\extensions\video_loopback_for_webui\scripts\video_loopback.py", line 500, in run
    reference_img_ques = [

IndexError: list index out of range

**Comment by keyskull** [comment]
The issue was probably caused by the input_directory variable when I use MP4 format video file as  the input file

**Comment by fishslot** [comment]
Can you put the full error message here? Preferably with the json file generated by the script?
