### ISSUE TITLE
AssertionError:

### ISSUE THREAD

**Issue by ScipidastrInc** [fishslot/video_loopback_for_webui#21]
In attempt of creating video using read_prompt_from_txt i get this erro. Anybody know how to fix it?

*** Error completing request
*** Arguments: ('task(9kj1e910zwkpjq3)', 0, 'a Holographic Shiny Iridescent metal Liquid Fluid', '', [], <PIL.Image.Image image mode=RGBA size=1694x899 at 0x25FC4A7DB40>, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 1, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x0000025FC4A7E1D0>, 10, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, True, False, 0, 'Range', 1, 'GPU', True, False, False, False, False, 0, 448, False, 448, False, False, 3, False, 3, True, 3, False, 'Horizontal', False, False, 'u2net', False, True, True, False, 0, 2.5, 'polylines_sharp', ['left-right', 'red-cyan-anaglyph'], 2, 0, '∯boost∯clipdepth∯clipdepth_far∯clipdepth_mode∯clipdepth_near∯compute_device∯do_output_depth∯gen_normalmap∯gen_rembg∯gen_simple_mesh∯gen_stereo∯model_type∯net_height∯net_size_match∯net_width∯normalmap_invert∯normalmap_post_blur∯normalmap_post_blur_kernel∯normalmap_pre_blur∯normalmap_pre_blur_kernel∯normalmap_sobel∯normalmap_sobel_kernel∯output_depth_combine∯output_depth_combine_axis∯output_depth_invert∯pre_depth_background_removal∯rembg_model∯save_background_removal_masks∯save_outputs∯simple_mesh_occlude∯simple_mesh_spherical∯stereo_balance∯stereo_divergence∯stereo_fill_algo∯stereo_modes∯stereo_offset_exponent∯stereo_separation', 'C:\\Users\\user\\Downloads\\water-flow2.mov', 'C:\\Users\\user\\Downloads\\', False, '', 127, True, 30, 9999, 1, True, 10, 0.25, True, False, 'simple', '1', 'lambda img: img.filter(ImageFilter.EDGE_ENHANCE).filter(ImageFilter.SMOOTH) if loop_i in {5,8} else img', True, '', '', '', '', '', '', '', '', '', '', '', '', 'FastDVDNet', 0.3, 60) {}
    Traceback (most recent call last):
      File "D:\GitHub\StableDiffusion\WebUI\stable-diffusion-webui\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\GitHub\StableDiffusion\WebUI\stable-diffusion-webui\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\GitHub\StableDiffusion\WebUI\stable-diffusion-webui\modules\img2img.py", line 236, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\GitHub\StableDiffusion\WebUI\stable-diffusion-webui\modules\scripts.py", line 700, in run
        processed = script.run(p, *script_args)
      File "D:\GitHub\StableDiffusion\WebUI\stable-diffusion-webui\extensions\video_loopback_for_webui\scripts\video_loopback.py", line 482, in run
        assert input_dir.exists()
    AssertionError

**Comment by fishslot** [comment]
```
assert input_dir.exists()
AssertionError
```
This mean, maybe your Input Directory dose not exist
