### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by JekkaBoi** [fishslot/video_loopback_for_webui#3]
Hi! Thanks for your works! I'm interested using this script. But, I've found this error below using Google Colab. Any idea for this problems? Thank you!

Arguments: ('task(a09gg36jodp9ng1)', 0, '', '2d, 3d, illustration, cartoon, manga, anime, text, signature, watermark', [], <PIL.Image.Image image mode=RGBA size=896x1280 at 0x7F7E78C32B20>, None, None, None, None, None, None, 20, 3, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.45, -1.0, -1.0, 0, 0, 0, False, 360, 480, 0, 0, 32, 0, '', '', '', [], 10, 'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUTS:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', False, 0, 'values', '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1', 'BASE,IN01,IN02,IN04,IN05,IN07,IN08,M00,OUT03,OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, [], '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2, '/content/gdrive/MyDrive/input', '/content/gdrive/MyDrive/output', False, '', 127, False, 30, 9999, 1, 10, 0.25, True, False, '1', True, '', '', '', '', '', '', '', '', '', '', '', 'None', 0.3, 60) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/img2img.py", line 167, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/video_loopback_for_webui/scripts/video_loopback.py", line 464, in run
    img_que = TemporalImageBlender(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/video_loopback_for_webui/scripts/video_loopback.py", line 33, in __init__
    self.window = deque(
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/video_loopback_for_webui/scripts/video_loopback.py", line 34, in <genexpr>
    self.read_image_resize(image_path_list[i])
IndexError: list index out of range

**Comment by zdunker** [comment]
Hello, how did you get this fixed? I'm running into the same error
