### ISSUE TITLE
Output is not what is displayed in preview (original images w/o the processing are saved)

### ISSUE THREAD

**Issue by CCpt5** [fishslot/video_loopback_for_webui#5]
Hello,

I'm attempting to try your extension today on a movie clip that I extracted to 15fps .PNGs. I've set the input folder to the folder w/ the PNGs, and an output folder. When I start the processing the preview shows good results, but it seems like the files saved in the output folder (in /out_frames/loop_1) aren't what is displayed in the preview window, but instead the originals.

I may be misunderstanding how to properly set the parameters, or exactly what is required to do the task, but if it should be saving the images I'm seeing in preview (which look good to me) please advise on what I might be doing incorrectly.

Thanks so much for a cool plugin!

---

Edit: 

Or does it do 2-passes? One as original IMG2IMG, then again after blurring to limit changes? Sorry if I'm asking newbie type questions. Thx

**Comment by fishslot** [comment]
The generated image by SD will mix with the input image, and then, output the mixed image for next loop. The displayed image is generated image, so, if you find it's not look like the output image, it's normal. You can change the `superimpose_alpha`, the larger it is, the closer the resulting image will be to the generated image, but at the same time this will make the resulting video look flickering.
From personal experience, I think it's better to use low `superimpose_alpha` and high `loop_n`, this will increase the temporal consistency and reduce flicker. 2-passes are not enough, usually more than 5 is better, both demo videos use 10 passes.
(I'm not too confident in my English and I refer to chatgpt results when writing the documentation, so it may look a bit confusing.  TAT )

**Comment by CCpt5** [comment]
Ok great - I'll have to play around more. I was attempting to use it on a clip that was 5min (I have brand new workstation w/ 4090), but I'll try something only a few second long to the hang of it.  
  
Thanks again (and sorry for posting this in "issues" since it's more of a ultimately it's a usage question).
