### ISSUE TITLE
The script ignores the resize mode you select in img2img settings

### ISSUE THREAD

**Issue by Giganoob23** [fishslot/video_loopback_for_webui#6]
I don't wanna use a 1:1 aspect ratio video. I went with a standard 16:9 video. I also don't wanna use crazy dimensions for the generated image because that will make the process much slower. I just want it to crop the right and left parts and make it a square. So I select the function that already exists to do that, "Crop and resize".

Still, the script ignores that, and it does the "just resize" option, which just squeezes the 16:9 frames down to 1:1 and makes the results horrible.

Please make it so that it listens to the resize mode option or we are forced to use only 1:1 videos and we all know square videos simply don't exist, and can't be arsed to edit videos to crop them.

**Comment by fishslot** [comment]
Very valuable suggestion, I will add this to my to-do list. Until I'm done, you can use www.birme.net as a substitute.
