### ISSUE TITLE
Images become more and more red with each loopback.

### ISSUE THREAD

**Issue by Giganoob23** [fishslot/video_loopback_for_webui#7]
I remember this was a general issue in A111 with the existing loopback script as well, but they had somehow fixed it. Using this script however the issue is reintroduced. Every loop adds a tiny bit of redness to the image. So when using the default 10 loops, the end result looks much more red/pink than the original

**Comment by fishslot** [comment]
This is an interesting phenomenon, I haven't had a similar problem in my previous tests. I had a situation where the video would get darker after processing, but once I set the VAE correctly, the problem disappeared. Can you provide more information so I can reproduce this issue?

**Comment by Giganoob23** [comment]
Using all default settings, using default SD 1.5 VAE, 7 CFG, around 0.33 denoising. Nothing special.

For the extension's settings, all default as I said (10 loopbacks, default alphas, not messing with advanced etc).

The only thing I didn't use is a controlnet. Will try again with that and see if it helps...
