### ISSUE TITLE
ControlNet not able to be used in a Batch process with Video Loopback

### ISSUE THREAD

**Issue by FizzleDorf** [fishslot/video_loopback_for_webui#8]
Hello, 
I was doing some tests with video loopback and noticed only the first frame would be used since controlnet uses the batch process of A1111 to receive images sequentially. Right now, the script uses it's own in/out directories so there isn't a way to take that as an input other than being able to use webui batch img2img. I understand this script isn't able to work in batch img2img at the moment. Can this get fixed? Controlnet has an img2img override that skips the img2img process as well. I think this could be a very accurate way of rotoscoping that requires less loops to accomplish. Thanks for your response in return.

**Comment by fishslot** [comment]
You can process an video or a batch for frames on the img2img tab or inpainting tab, all the functions of this script is available even without the batch-img2img tab. You're having problems with the script only processing the first image, does this problem still occur when you're on an img2img tab? Have you check the `Settings->ControlNet->Allow other script to control this extension` ?
In the batch-img2img tab, users can't change the `Masked content` , and I think it's a little inconvenient.
This script already supports use with controlnet, all its functions are working properly with video loopback, according to my personal tests.
Of course, I'll add support for batch-img2img tab to the script later, but since this doesn't bring new functionality, this feature may be postponed for a few days before consideration.

**Comment by fishslot** [comment]
I may have some misunderstandings. Are you not able to use this script properly at all? Or are you able to use this script normally, you just can't use this script together with controlnet? Or, are you able to use it normally at all and just want it to work under the batch-img2img tab as well?

**Comment by Giganoob23** [comment]
> I may have some misunderstandings. Are you not able to use this script properly at all? Or are you able to use this script normally, you just can't use this script together with controlnet? Or, are you able to use it normally at all and just want it to work under the batch-img2img tab as well?

I think his issue is that he forgot to check the setting where it says allow scripts to use controlnet. So when he tries using controlnet with your script, controlnet keeps generating the same image for every frame. Happened to me before.

**Comment by FizzleDorf** [comment]
@fishslot the script works normally but with strange behavior. The setting for use control net is enabled and ControlNet seems to be working (the openpose images can't be printed in a batch process at the time I attempted to use it so I can't know for sure). The latter part of what @Giganoob23 is saying is true in a way. The new image being blended in the loops is always the same image. Apologies I can't show any examples at the moment, I am away for the weekend but I hope this clarifies what the issue is.

**Comment by fishslot** [comment]
Can you provide more information so I can reproduce this issue? Have you applied your settings after you change it?

**Comment by FizzleDorf** [comment]
Steps to reproduce is just regular use + controlnet. I did 2 default runs in img2img with ~120 frames (use 10 frames for debugging). The input image was the first frame of the batch and controlnet was set to openpose for the preprocessor and model. Settings were applied before the generation as the readme suggested. Just a clarification for what is going on too. Controlnet can only receive a new image for a batch from the webui batch img2img tab. If it is in img2img tab, it reuses the same image. If video loopback were to work in batch img2img, the controlnet image would change to the appropriate frame.

**Comment by fishslot** [comment]
It sounds terrible. So you won't have any problems using this script with controlnet disabled, the problem only occurs when controlnet is enabled, right? Can you upload the json file generated by the script? Or just copy the contents here. If you could provide the generated frames and input frames, maybe that would allow me to locate the problem faster.

**Comment by FizzleDorf** [comment]
Unfortunately I won't be able to until tomorrow. I am away from my machine right now but I will provide examples and the json file when I am able. Apologies I can't do it sooner.

**Comment by FizzleDorf** [comment]
After rigorous testing yesterday to be absolutely sure about the problem. It was a controlnet issue all along. I did find a use for this issue to "leak" controlnet processing into other extensions. Apologies I couldn't find the root of the problem sooner. Thanks for all your work and help!
